### ISSUE TITLE
1.12.2 Cascading Worldgen Lag

### ISSUE THREAD

**Issue by TBye101** [ferreusveritas/Dynamic-Trees#117]
Just letting you guys know about this...

This happens about every new chunk in my server.

[13:41:11] [Server thread/WARN] [FML]: Dynamic Trees loaded a new chunk [-5, -48] in dimension 0 (overworld) while populating chunk [-5, -46], causing cascading worldgen lag.
[13:41:11] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

**Comment by ghost** [comment]
These errors are kinda hard to track.  I have a breakpoint set for when it happens in my dev environment and I promptly fix it.  I hardly ever get these errors anymore as I've fixed most of them.  Since a proper crash log isn't generated I just have to wait until I experience it myself as there's no telling where the problem originates from.

In what biome do you tend to experience this the most?

**Comment by TBye101** [comment]
Alright, good luck!

Thanks for the response.
________________________________

**Comment by JamesATeasdale** [comment]
i'm getting a lot of cascading worldgen errors too in the foresthills.

**Comment by AlyceOsbourne** [comment]
I too get massive cascades to the point my computer freezes completely (I have plenty of power to run this and some)

**Comment by LatvianModder** [comment]
Still an issue
![](https://user-images.githubusercontent.com/3844385/64480304-05a9e800-d1ce-11e9-9735-29989bd1aad3.png)
I think the fix was to offset x and z by 8 or something, but I'm not sure

**Comment by Morilli** [comment]
Getting this too.
