### ISSUE TITLE
Dynamic Tree Strange Texture

### ISSUE THREAD

**Issue by StellaBiscuit** [ferreusveritas/Dynamic-Trees#298]
**Describe the bug**
All "Vanilla" Dynamic trees have texture glitch. (Also happen on addon trees that use Vanilla tree texture)

**To Reproduce**
???

**Screenshots**
![2019-08-08_15 40 19](https://user-images.githubusercontent.com/53101126/62732927-83be7780-b9f3-11e9-8160-59f3f72ec678.png)
![2019-08-08_15 42 40](https://user-images.githubusercontent.com/53101126/62732929-85883b00-b9f3-11e9-8e61-affdd562d530.png)

**Rendering Glitches**
Are you using Optifine?
No

**Additional context**
I'm making a modpack so I don't know which mod combination cause the issue. But I think it's better foliage

**Mods List**
I mod that are bold or the mod that could cause the issue

The Betweenlands
Actually Addition
AE2 Stuff
AE2 Wireless Terminal Library
AlwaysEat
Ambience (Music Mod)
AppleCore
AppleSkin
Applied Energistics 2
ArmorPlus
ArtemisLib
Astral Sorcery
AutoRegLib
**Auxiliary Biomes**
Avaritia
Baubles
BdLib
Bedrock Miner
Better Advancements
Better Builder's Wands
**Better Foliage**
Better Questing
Better Questing - Quest Book
Better Questing - Standard Expansion
Better Questing Triggerer
Bigger Crafting Tables
**Biomes O' Plenty**
Blood Magic
BnBGamingCore
BNBGamingLib
**Bonsai Trees**
Bookshelf
Botania
Brandon's Core
Ceramics
Chameleon
Chisel
Chisels & Bits
Clumps
CodeChicken Lib
CoFH Core
CoFH World
Combustive Fishing
Compact Machines
**ConnectedTexturesMod**
Construct's Armory
Cooking for Blockheads
CraftTweaker
Cucumber Library
Culinary Construct
Custom Crafting Tables
Custom Disc
Custom Main Menu
Dark Utilities
Dead Wood
Dimension Stages
Draconic Evolution
_Dynamic Trees_
_Dynamic Trees - Biomes O' Plenty Compat_
_Dynamic Trees - Pam's Harvestcraft Compat_
_Dynamic Trees - Thaumcraft Compat_
_Dynamic Trees - Traverse Compat_
Ender IO
Ender IO Endergy
Ender Storage
Ender Tweaker
EnderCore
Environmental Tech
Extended Crafting
Extra Utilities
ExtraCells2
Extreme Reactors
Farming for Blockheads
Fast Leaf Decay
FastWorkbench
**Forestry**
FTB Library
FTB Utilities
Game Stages
Guide-API
Hardcore Item Stages
Hatchery
Hunger Overhaul
Hwyla
iChunUtil
Immersive Engineering
Industrial Foregoing
Integration Foregoing
Iron Backpacks
Iron Chests
Item Stages
JAOPCA
JAOPCAAdditions
JAOPCAAgriculture
JAOPCACustom
JAOPCASingularities
JourneyMap
Just Enough Items
Kitsu's ForgeCraft
MalisisCore
MalisisDoors
Mantle
McJtyLib
Mekanism
Mekanism Generators
Metallurgy 4: Reforged
Minestrappolation 5
Mob Stages
More Overlays
Mouse Tweaks
MultiBlock Stages
Mystical Agradditions
Mystical Agriculture
**Natura**
Neat
No More Punching Tree
No Recipe Book
**NotEnoughIDs**
Ore Excavation
Ore Excavation
Ore Stages
p455w0rd's Library
Pam's HarvestCraft
Pam's Redbud Tree
Pam's Spooky Tree
Patchouli
Pewter
PlusTiC
Primal Tech
**PrimalCore**
Primitive Crafting
ProjectE
Quadrum
Quark
Recipe Stages
Redstone Flux
**Redwoods**
Resizing Potion
Resource Loader
RFTools
Shadowfacts' Forgelin
Silent Lib
Silent's Gems
Simply Bedrock
Simply Jetpacks 2
**Sky Orchards**
Spice of Life: Carrot Edition
Stage Tabels
Storage Drawers
Tesla Core Lib
Thaumcraft
The One Probe	McJty
The Spice of Life
**The Twilight Forest**
TheDragonLib
Thermal Cultivation
Thermal Dynamics
Thermal Expansion
Thermal Foundation
Thermal Innovation
Thermal Tinkering
Time Stages
Tinkers Construct
Tinkers' Tool Leveling
Tips
Tool Progression
Tough As Nails
Tough Expansion
**Traverse Legacy**
Triumph
UniDict
ValkyrieLib
Waila Stages
WanionLib
Wireless Crafting Terminal
WrapUp
ZeroCore

Minecraft is on 1.12.2

**Comment by StellaBiscuit** [comment]
Also all the mods are at there latest version for now. I will say if it's accidently corrected by a mod update

**Comment by kierajreed** [comment]
Please narrow down the offending mods using binary search. Thanks.

**Comment by Inf0214** [comment]
Have the same issue, will look into which mod it could be, strange thing is that it was working fine yesterday I removed RTG to test a world pregen mod that was incompatible. Thats when I first saw it, now I removed that mod and added RTG back and had the same issue still.

**Comment by Inf0214** [comment]
After ~4 hours of testing I found it is caused by [Item Stages](https://www.curseforge.com/minecraft/mc-mods/item-stages). Once removed it worked fine. Looking into making it compatible via config.

**Comment by StellaBiscuit** [comment]
Thanks! Anyway, after some test, my modpack is really big and keeping the mod is not a good idea (performance) so I will remove it. But I will know it if I do an other modpack

**Comment by KatherineLee318** [comment]
its actually a issue with hardcore item stages hide item option.
once its set to false the issue goes away.
